name: rpmtw_translation_scripts
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  archive: ^3.1.5
  args: ^2.3.0
  dio: ^4.0.0
  gson: 0.1.6-dev
  path: ^1.8.0
  toml: ^0.12.0

