name: CI
 
on:
  push:
    branches: [ Translated ]
    paths:
    - '1.16/zh-TW/**'
    - '1.16/Add-on/**'
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1 #zipped file 1.16
        with:
          files: 1.16/zh-TW 1.16/Add-on
          dest: RPMTW-1.16.zip

      - name: Upload 1.16 release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RPMTW_BOT_TOKEN}}
          tag: RPMTW-1.16-V${{ github.run_number }}
          file: ${{ github.workspace }}/RPMTW-1.16.zip
          asset_name: RPMTW-1.16.zip
          overwrite: true
          body: "繁體中文化模組資源包(RPMTW) 版本:V${{ github.run_number }} \n更新內容: [${{ github.event.head_commit.message }}](https://github.com/SiongSng/ResourcePack-Mod-zh_tw/commit/${{ github.sha }})"
